
package com.owl_ontologies.ecsdiservices;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ReservesService", targetNamespace = "http://www.owl-ontologies.com/ECSDIServices", wsdlLocation = "file:/Users/clara/Dropbox/ECSDI/Practica/WSDL/ReservesService.wsdl")
public class ReservesService
    extends Service
{

    private final static URL RESERVESSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.owl_ontologies.ecsdiservices.ReservesService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.owl_ontologies.ecsdiservices.ReservesService.class.getResource(".");
            url = new URL(baseUrl, "file:/Users/clara/Dropbox/ECSDI/Practica/WSDL/ReservesService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/Users/clara/Dropbox/ECSDI/Practica/WSDL/ReservesService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        RESERVESSERVICE_WSDL_LOCATION = url;
    }

    public ReservesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReservesService() {
        super(RESERVESSERVICE_WSDL_LOCATION, new QName("http://www.owl-ontologies.com/ECSDIServices", "ReservesService"));
    }

    /**
     * 
     * @return
     *     returns ReservesPortType
     */
    @WebEndpoint(name = "ReservesPort")
    public ReservesPortType getReservesPort() {
        return super.getPort(new QName("http://www.owl-ontologies.com/ECSDIServices", "ReservesPort"), ReservesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReservesPortType
     */
    @WebEndpoint(name = "ReservesPort")
    public ReservesPortType getReservesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.owl-ontologies.com/ECSDIServices", "ReservesPort"), ReservesPortType.class, features);
    }

}
